-- 9. ERROR_LOG
-- Записи ошибок, произодъшедших во время работы симулятора
CREATE TABLE error_log (
    log_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    proc_name   VARCHAR2(100),
    user_id     NUMBER,
    error_code  VARCHAR2(20),
    error_msg   VARCHAR2(4000),
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE OR REPLACE PACKAGE pkg_logger AS
    PROCEDURE log_error(
        p_proc_name IN VARCHAR2,
        p_user_id   IN NUMBER DEFAULT NULL,
        p_err_code  IN VARCHAR2 DEFAULT NULL,
        p_err_msg   IN VARCHAR2
    );
END pkg_logger;
/

CREATE OR REPLACE PACKAGE BODY pkg_logger AS
    PROCEDURE log_error(
        p_proc_name IN VARCHAR2,
        p_user_id   IN NUMBER DEFAULT NULL,
        p_err_code  IN VARCHAR2 DEFAULT NULL,
        p_err_msg   IN VARCHAR2
    ) IS
        -- ! МАГИЯ: Эта транзакция живет отдельно от основной !
        PRAGMA AUTONOMOUS_TRANSACTION; 
    BEGIN
        INSERT INTO error_log (proc_name, user_id, error_code, error_msg)
        VALUES (p_proc_name, p_user_id, p_err_code, p_err_msg);
        
        COMMIT; -- Коммитим только лог, не затрагивая основную сделку
    EXCEPTION WHEN OTHERS THEN
        NULL; -- Если сломался логгер, мы ничего не можем сделать
    END log_error;
END pkg_logger;
/

-- Даем права
CREATE OR REPLACE PUBLIC SYNONYM pkg_logger FOR pkg_logger;
GRANT EXECUTE ON pkg_logger TO stock_guest;
GRANT EXECUTE ON pkg_logger TO stock_user;
GRANT EXECUTE ON pkg_logger TO stock_admin;