-- 10. NOTIFICATIONS
-- Хранит сами уведомления (содержание и тип)
CREATE TABLE NOTIFICATIONS (
    notification_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    title           VARCHAR2(200),
    message         VARCHAR2(1000),
    type            VARCHAR2(20) CHECK (type IN ('INFO', 'SUCCESS', 'WARNING', 'ERROR', 'TRADE')),
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 11. USER_NOTIFICATIONS
-- Хранит статус прочтения для конкретного пользователя
CREATE TABLE USER_NOTIFICATIONS (
    user_id         NUMBER REFERENCES users(user_id) ON DELETE CASCADE,
    notification_id NUMBER REFERENCES notifications(notification_id) ON DELETE CASCADE,
    is_read         NUMBER(1) DEFAULT 0 CHECK (is_read IN (0, 1)),
    delivered_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT pk_user_notif PRIMARY KEY (user_id, notification_id)
);


CREATE OR REPLACE PACKAGE pkg_notifications AS

    -- Создать личное уведомление (для одного юзера)
    PROCEDURE create_personal_notification (
        p_user_id   IN NUMBER,
        p_title     IN VARCHAR2,
        p_message   IN VARCHAR2,
        p_type      IN VARCHAR2,
        o_status    OUT VARCHAR2,
        o_message   OUT VARCHAR2
    );

    -- Получить список уведомлений пользователя
    PROCEDURE get_my_notifications (
        p_user_id      IN NUMBER,
        p_only_unread  IN NUMBER DEFAULT 0, -- 1 = только новые
        o_cursor       OUT SYS_REFCURSOR,
        o_status       OUT VARCHAR2,
        o_message      OUT VARCHAR2
    );

    -- Пометить уведомление как прочитанное
    PROCEDURE mark_as_read (
        p_user_id         IN NUMBER,
        p_notification_id IN NUMBER,
        o_status          OUT VARCHAR2,
        o_message         OUT VARCHAR2
    );
    
    PROCEDURE get_recent_notifications (
        p_user_id     IN  NUMBER,
        p_since_time  IN  TIMESTAMP,
        o_cursor      OUT SYS_REFCURSOR
    );

END pkg_notifications;
/

CREATE OR REPLACE PACKAGE BODY pkg_notifications AS

    PROCEDURE create_personal_notification (
        p_user_id   IN NUMBER,
        p_title     IN VARCHAR2,
        p_message   IN VARCHAR2,
        p_type      IN VARCHAR2,
        o_status    OUT VARCHAR2,
        o_message   OUT VARCHAR2
    ) IS
        v_notif_id NUMBER;
    BEGIN
        o_status := 'SUCCESS';
        o_message := 'Уведомление отправлено';
        
        PRAGMA AUTONOMOUS_TRANSACTION;
        -- 1. Создаем тело уведомления
        INSERT INTO notifications (title, message, type)
        VALUES (p_title, p_message, p_type)
        RETURNING notification_id INTO v_notif_id;

        -- 2. Связываем с пользователем
        INSERT INTO user_notifications (user_id, notification_id)
        VALUES (p_user_id, v_notif_id);

        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            stock_admin.pkg_logger.log_error('pkg_notifications.create_personal', p_user_id, SQLCODE, SQLERRM);
            o_status := 'ERROR';
            o_message := 'Internal Server Error';
    END create_personal_notification;

    PROCEDURE get_my_notifications (
        p_user_id      IN NUMBER,
        p_only_unread  IN NUMBER DEFAULT 0,
        o_cursor       OUT SYS_REFCURSOR,
        o_status       OUT VARCHAR2,
        o_message      OUT VARCHAR2
    ) IS
    BEGIN
        o_status := 'SUCCESS';
        o_message := 'ОК';

        OPEN o_cursor FOR
            SELECT n.notification_id, n.title, n.message, n.type, n.created_at, un.is_read
            FROM notifications n
            JOIN user_notifications un ON n.notification_id = un.notification_id
            WHERE un.user_id = p_user_id
              AND (p_only_unread = 0 OR un.is_read = 0)
            ORDER BY n.created_at DESC
            FETCH FIRST 50 ROWS ONLY; -- Ограничиваем список
    EXCEPTION
        WHEN OTHERS THEN
            stock_admin.pkg_logger.log_error('pkg_notifications.get_my_notifications', p_user_id, SQLCODE, SQLERRM);
            o_status := 'ERROR';
            o_message := 'Internal Server Error';
    END get_my_notifications;

    PROCEDURE mark_as_read (
        p_user_id         IN NUMBER,
        p_notification_id IN NUMBER,
        o_status          OUT VARCHAR2,
        o_message         OUT VARCHAR2
    ) IS
    BEGIN
        o_status := 'SUCCESS';
        o_message := 'Прочитано';

        UPDATE user_notifications
        SET is_read = 1
        WHERE user_id = p_user_id AND notification_id = p_notification_id;
        
        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            o_status := 'ERROR';
            o_message := 'Internal Server Error';
    END mark_as_read;

    PROCEDURE get_recent_notifications (
        p_user_id     IN  NUMBER,
        p_since_time  IN  TIMESTAMP,
        o_cursor      OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN o_cursor FOR
            SELECT n.notification_id, n.title, n.message, n.type, n.created_at, un.is_read
            FROM notifications n
            JOIN user_notifications un ON n.notification_id = un.notification_id
            WHERE un.user_id = p_user_id
              AND n.created_at > p_since_time -- Только свежие
            ORDER BY n.created_at ASC;
    END get_recent_notifications;

END pkg_notifications;
/

GRANT EXECUTE ON pkg_notifications TO stock_user;
GRANT EXECUTE ON pkg_notifications TO stock_admin;