GRANT EXECUTE ON DBMS_LOCK TO STOCK_ADMIN;
GRANT CREATE JOB TO stock_admin;
GRANT MANAGE SCHEDULER TO stock_admin;
alter session set container =  STOCKLABDB;
show pdbs;

-- 12. BOT_CONFIGS 
-- Конфиги ботов (черты характера агента, определяющие подход к торговле)
CREATE TABLE BOT_CONFIGS (
    user_id       NUMBER PRIMARY KEY,
    greed_factor  NUMBER(4,2) DEFAULT 1.05, -- Жадность: множитель для продажи в плюс (1.05 = +5%)
    panic_level   NUMBER(4,2) DEFAULT 0.95, -- Паника: множитель для стоп-лосса (0.95 = -5%)
    memory_span   NUMBER(4)   DEFAULT 3, -- Память: сколько тиков назад смотрим (1-20)
    bet_size      NUMBER(4,2) DEFAULT 0.5, -- Риск: доля баланса в сделку (0.1 - 1.0)

    CONSTRAINT fk_bc_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);
-- 13. TOURNAMENTS
-- Турниры ( соревнования по определению лучших ботов для аналитики конфигураций)
CREATE TABLE TOURNAMENTS (
    tournament_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    status_id     NUMBER DEFAULT 0 NOT NULL, 
    start_time    TIMESTAMP DEFAULT SYSTIMESTAMP,
    end_time      TIMESTAMP,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 14. NETWORTH_SNAPSHOTS
-- Снэпшоты состояния (состояние бота на начало турнира)
CREATE TABLE NETWORTH_SNAPSHOTS (
    tournament_id  NUMBER NOT NULL,
    user_id        NUMBER NOT NULL,
    start_networth NUMBER NOT NULL,
    start_time     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    
    PRIMARY KEY (tournament_id, user_id),
    CONSTRAINT fk_ns_tourn FOREIGN KEY (tournament_id) REFERENCES tournaments(tournament_id),
    CONSTRAINT fk_ns_user  FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- 15. TOURNAMENT_HISTORY
-- История турнира(итоги турнира для бота)
CREATE TABLE TOURNAMENT_HISTORY (
    tournament_id  NUMBER NOT NULL,        
    user_id        NUMBER NOT NULL,        
    final_roi      NUMBER(10,2),  
    final_rank     NUMBER(5),     
    tier_id        NUMBER,     
    
    PRIMARY KEY (tournament_id, user_id),
    CONSTRAINT fk_th_tourn FOREIGN KEY (tournament_id) REFERENCES tournaments(tournament_id),
    CONSTRAINT fk_th_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);
