ALTER PLUGGABLE DATABASE stocklabdb CLOSE IMMEDIATE;
DROP PLUGGABLE DATABASE stocklabdb INCLUDING DATAFILES;
CREATE PLUGGABLE DATABASE stocklabdb
FILE_NAME_CONVERT=('/opt/oracle/oradata/FREE/pdbseed/','/opt/oracle/oradata/FREE/stocklabdb/')
ADMIN USER stock_admin IDENTIFIED BY "admin123!"
ROLES = (DBA);
ALTER PLUGGABLE DATABASE stocklabdb OPEN;
ALTER PLUGGABLE DATABASE stocklabdb SAVE STATE;