-- 1. ROLES
-- Определяет роль пользователя
CREATE TABLE ROLES (
    role_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(50) NOT NULL UNIQUE
);

-- 2. USERS
-- Основная информация о пользователе.
CREATE TABLE USERS (
    user_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    role_id     NUMBER NOT NULL,
    username    VARCHAR2(50) NOT NULL UNIQUE,
    email   VARCHAR2(100) NOT NULL UNIQUE,
    password_hash   VARCHAR2(255) NOT NULL,
    balance NUMBER(15,2) NOT NULL DEFAULT 0,
    is_banned NUMBER(1) NOT NULL DEFAULT 0 CHECK(is_banned in (0,1)),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(role_id),
);
-- 3. SECTORS
-- Сектора экономики
CREATE TABLE SECTORS (
    sector_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL UNIQUE,
    description VARCHAR2(500)
);

-- 4. COMPANIES
-- Компании,которые торгуются
CREATE TABLE COMPANIES (
    company_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    sector_id      NUMBER NOT NULL,
    name           VARCHAR2(100) NOT NULL UNIQUE,
    ticker_symbol  VARCHAR2(10) NOT NULL UNIQUE,
    description    VARCHAR2(1000),
    current_price  NUMBER(10, 2) DEFAULT 0 NOT NULL,
    volatility_factor NUMBER(5, 2) DEFAULT 0.05,
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'DELISTED', 'BANKRUPT')),
    total_shares NUMBER DEFAULT 1000000 NOT NULL,
    last_trade_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    
    CONSTRAINT fk_companies_sector FOREIGN KEY (sector_id) REFERENCES sectors(sector_id),
    CONSTRAINT chk_company_price CHECK (current_price >= 0),
    CONSTRAINT chk_volatility CHECK (volatility_factor > 0 AND volatility_factor <= 10)
);

-- 5. PRICE_LOG
-- Логи цен для графиков
CREATE TABLE PRICE_LOG (
    log_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    company_id  NUMBER NOT NULL,
    price       NUMBER(10, 2) NOT NULL,
    log_time    TIMESTAMP DEFAULT SYSTIMESTAMP,
    
    CONSTRAINT fk_log_company FOREIGN KEY (company_id) REFERENCES companies(company_id)
);

-- 6. ORDERS
-- Оредера на продажу или покупку акций
CREATE TABLE ORDERS (
    order_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id        NUMBER NOT NULL,
    company_id     NUMBER NOT NULL,
    type           VARCHAR2(4) NOT NULL CHECK (type IN ('BUY', 'SELL')),
    status         VARCHAR2(10) DEFAULT 'OPEN' NOT NULL CHECK (status IN ('OPEN', 'PARTIAL', 'FILLED', 'CANCELLED')),
    limit_price    NUMBER(10, 2) NOT NULL,
    original_qty   NUMBER NOT NULL CHECK (original_qty > 0),
    remaining_qty  NUMBER NOT NULL CHECK (remaining_qty >= 0),
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP,
    
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_orders_company FOREIGN KEY (company_id) REFERENCES companies(company_id)
);

-- 7. TRADES
-- Совершенные сделки
CREATE TABLE TRADES (
    trade_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    buyer_order_id  NUMBER NOT NULL,
    seller_order_id NUMBER NOT NULL,
    company_id      NUMBER NOT NULL,
    trade_price     NUMBER(10, 2) NOT NULL,
    quantity        NUMBER NOT NULL CHECK (quantity > 0),
    executed_at     TIMESTAMP DEFAULT SYSTIMESTAMP,
    
    CONSTRAINT fk_trade_buyer FOREIGN KEY (buyer_order_id) REFERENCES orders(order_id),
    CONSTRAINT fk_trade_seller FOREIGN KEY (seller_order_id) REFERENCES orders(order_id),
    CONSTRAINT fk_trade_company FOREIGN KEY (company_id) REFERENCES companies(company_id)
);

-- 8. PORTFOLIOS
-- Имеющиеся активы компаний у пользователей
CREATE TABLE PORTFOLIOS (
    user_id        NUMBER NOT NULL,
    company_id     NUMBER NOT NULL,
    quantity_owned NUMBER DEFAULT 0 NOT NULL,
    
    CONSTRAINT pk_portfolio PRIMARY KEY (user_id, company_id),
    CONSTRAINT fk_portfolio_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_portfolio_company FOREIGN KEY (company_id) REFERENCES companies(company_id),
    CONSTRAINT chk_portfolio_qty CHECK (quantity_owned >= 0)
);

-- 
INSERT INTO ROLES (NAME) VALUES ('Admin');
INSERT INTO ROLES (NAME) VALUES ('User');
INSERT INTO ROLES (NAME) VALUES ('Bot');
INSERT INTO ROLES (NAME) VALUES ('Issuer');
COMMIT;


CREATE INDEX IDX_USERS_ROLE ON USERS(ROLE_ID)
    TABLESPACE stocklab_index;

CREATE INDEX IDX_COMPANIES_SECTOR ON COMPANIES(SECTOR_ID)
    TABLESPACE stocklab_index;

CREATE INDEX IDX_TRADES_COMP_TIME ON TRADES(COMPANY_ID, EXECUTED_AT)
    TABLESPACE stocklab_index;

CREATE INDEX IDX_LOG_COMP_TIME ON PRICE_LOG(COMPANY_ID, LOG_TIME)
    TABLESPACE stocklab_index;

CREATE INDEX IDX_COMPANIES_LAST_TRADE ON COMPANIES(LAST_TRADE_AT)
    TABLESPACE stocklab_index;

CREATE INDEX IDX_ORDERS_MATCHING ON ORDERS(COMPANY_ID, STATUS, TYPE, LIMIT_PRICE)
    TABLESPACE stocklab_index;

CREATE INDEX IDX_UNOTIF_USER_READ ON USER_NOTIFICATIONS(USER_ID, IS_READ)
    TABLESPACE stocklab_index;