alter session  set container = STOCKLABDB;
show con_name;
-- ===========================================================
--  SCHEMA: STOCKLABDB
--  SECTION: CORE TABLE STRUCTURE
-- ===========================================================

-- ===========================================================
-- TABLE: SECTORS
-- ===========================================================
CREATE TABLE Sectors (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(100) NOT NULL UNIQUE,
    description     VARCHAR2(400),
    buff            NUMBER(5,2) DEFAULT 0 CHECK (buff BETWEEN -100 AND 100)
);

-- ===========================================================
-- TABLE: COMPANIES
-- ===========================================================
CREATE TABLE Companies (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sector_id           NUMBER NOT NULL,
    name                VARCHAR2(150) NOT NULL UNIQUE,
    description         VARCHAR2(400),
    buff                NUMBER(5,2) DEFAULT 0,
    earnings            NUMBER(14,2) DEFAULT 0 CHECK (earnings >= 0),
    spendings           NUMBER(14,2) DEFAULT 0 CHECK (spendings >= 0),
    dividend_percentage NUMBER(5,2) DEFAULT 0 CHECK (dividend_percentage BETWEEN 0 AND 100),
    dividend_date       DATE,
    evaluation          NUMBER(18,2) DEFAULT 0 CHECK (evaluation >= 0),
    current_price       NUMBER(14,2) DEFAULT 0 CHECK (current_price >= 0),

    CONSTRAINT fk_companies_sector FOREIGN KEY (sector_id)
        REFERENCES sectors(id) ON DELETE CASCADE
);

CREATE INDEX idx_companies_sector ON companies(sector_id);
CREATE INDEX idx_companies_name ON companies(name);

-- ===========================================================
-- TABLE: EVENTS
-- ===========================================================
CREATE TABLE Events (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      NUMBER,
    sector_id        NUMBER,
    headline        VARCHAR2(200) NOT NULL,
    description     VARCHAR2(1000),
    effect          NUMBER(6,2) DEFAULT 0,
    event_date      DATE DEFAULT SYSDATE,

    CONSTRAINT fk_events_company FOREIGN KEY (company_id) REFERENCES Companies(id),
    CONSTRAINT fk_events_sector FOREIGN KEY (sector_id) REFERENCES Sectors(id)
);

CREATE INDEX idx_events_company ON events(company_id);
CREATE INDEX idx_events_date ON events(event_date);

-- ===========================================================
-- TABLE: USERS
-- ===========================================================
CREATE TABLE Users (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR2(100) UNIQUE NOT NULL,
    password    VARCHAR2(255) NOT NULL,
    role        VARCHAR2(20) CHECK (role IN ('ADMIN', 'USER', 'GUEST')),
    balance     NUMBER(14,2) DEFAULT 0 CHECK (balance >= 0),
    created_at  DATE DEFAULT SYSDATE
);

CREATE INDEX idx_users_role ON users(role);

-- ===========================================================
-- TABLE: STOCK
-- ===========================================================
drop table stock;
CREATE TABLE stocks (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      NUMBER NOT NULL,
    portolio_id        NUMBER,
    purchase_price  NUMBER(14,2) DEFAULT 0 CHECK (purchase_price >= 0),
    acquired_date   DATE DEFAULT SYSDATE,
    status          VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'LISTED_FOR_SALE', 'SUSPENDED')),
    listing_price   NUMBER(14,2) CHECK (listing_price >= 0),
    last_trade_id   NUMBER,

    CONSTRAINT fk_stock_company FOREIGN KEY (company_id) REFERENCES companies(id),
    CONSTRAINT fk_stock_owner FOREIGN KEY (owner_id) REFERENCES portfolios(user_id)
);


CREATE INDEX idx_stock_owner ON stock(owner_id);
CREATE INDEX idx_stock_company ON stock(company_id);
CREATE INDEX idx_stock_status ON stock(status);

-- ===========================================================
-- TABLE: TRADES
-- ===========================================================
drop table trades;
CREATE TABLE trades (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id        NUMBER NOT NULL,
    seller_id       NUMBER NOT NULL,
    stock_id        NUMBER NOT NULL,
    trade_price     NUMBER(14,2) NOT NULL CHECK (trade_price >= 0),
    trade_date      DATE DEFAULT SYSDATE,

    CONSTRAINT fk_trade_buyer FOREIGN KEY (buyer_id) REFERENCES users(id),
    CONSTRAINT fk_trade_seller FOREIGN KEY (seller_id) REFERENCES users(id),
    CONSTRAINT fk_trade_stock FOREIGN KEY (stock_id) REFERENCES stock(id)
);

CREATE INDEX idx_trades_stock ON trades(stock_id);
CREATE INDEX idx_trades_date ON trades(trade_date);

-- ===========================================================
-- TABLE: PRICE_LOG
-- ===========================================================
CREATE TABLE price_log (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id        NUMBER NOT NULL,
    trade_id        NUMBER,
    trade_date      DATE DEFAULT SYSDATE,
    price           NUMBER(14,2) NOT NULL CHECK (price >= 0),

    CONSTRAINT fk_pricelog_stock FOREIGN KEY (stock_id) REFERENCES stock(id),
    CONSTRAINT fk_pricelog_trade FOREIGN KEY (trade_id) REFERENCES trades(id)
);

CREATE INDEX idx_pricelog_stock ON price_log(stock_id);
CREATE INDEX idx_pricelog_date ON price_log(trade_date);
