CREATE TABLE roles (
    id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR2(50) UNIQUE NOT NULL
);

INSERT INTO roles (name) VALUES ('ADMIN');
INSERT INTO roles (name) VALUES ('USER');
INSERT INTO roles (name) VALUES ('GUEST');
INSERT INTO roles (name) VALUES ('BOT');
select * from users;

CREATE TABLE users (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id         NUMBER NOT NULL,
    username        VARCHAR2(100) UNIQUE NOT NULL,
    password_hash   VARCHAR2(255) NOT NULL,
    email           VARCHAR2(200) UNIQUE,
    balance         NUMBER(14,2) DEFAULT 0 CHECK (balance >= 0),
    trade_count     NUMBER DEFAULT 0 CHECK (trade_count >= 0),
    is_bot          CHAR(1) DEFAULT 'N' CHECK (is_bot IN ('Y','N')),
    is_banned       CHAR(1) DEFAULT 'N' CHECK (is_banned IN ('Y','N')),
    created_at      DATE DEFAULT SYSDATE,

    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE INDEX idx_users_role ON users(role_id);
CREATE INDEX idx_users_isbot ON users(is_bot);
CREATE INDEX idx_users_isbanned ON users(is_banned);

CREATE TABLE portfolios (
    user_id         NUMBER PRIMARY KEY,
    created_at      DATE DEFAULT SYSDATE,
    last_updated_at DATE DEFAULT SYSDATE,

    CONSTRAINT fk_portfolio_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE achievements (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(100) UNIQUE NOT NULL,
    description     VARCHAR2(400),
    icon_path       VARCHAR2(255)
);
CREATE TABLE user_achievements (
    user_id         NUMBER NOT NULL,
    achievement_id  NUMBER NOT NULL,
    achieved_at     DATE DEFAULT SYSDATE,

    CONSTRAINT pk_user_achievements PRIMARY KEY (user_id, achievement_id),
    CONSTRAINT fk_user_ach_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_ach_ach FOREIGN KEY (achievement_id) REFERENCES achievements(id) ON DELETE CASCADE
);

CREATE INDEX idx_user_ach_user ON user_achievements(user_id);

CREATE TABLE upgrades (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_upgrade_id   NUMBER,
    name                VARCHAR2(100) NOT NULL,
    description         VARCHAR2(400),
    tier                NUMBER(3) DEFAULT 1 CHECK (tier >= 1),
    branch              VARCHAR2(50),
    icon_path           VARCHAR2(255),

    CONSTRAINT fk_upgrades_parent FOREIGN KEY (parent_upgrade_id) REFERENCES upgrades(id)
);

CREATE INDEX idx_upgrades_branch ON upgrades(branch);
CREATE INDEX idx_upgrades_tier ON upgrades(tier);

CREATE TABLE user_upgrades (
    user_id         NUMBER NOT NULL,
    upgrade_id      NUMBER NOT NULL,
    acquired_at     DATE DEFAULT SYSDATE,

    CONSTRAINT pk_user_upgrades PRIMARY KEY (user_id, upgrade_id),
    CONSTRAINT fk_user_up_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_up_upgrade FOREIGN KEY (upgrade_id) REFERENCES upgrades(id) ON DELETE CASCADE
);

--todo
CREATE TABLE bot_configs (
    user_id             NUMBER PRIMARY KEY,
    trade_frequency     NUMBER(3) DEFAULT 5 CHECK (trade_frequency >= 0),
    aggression_level    NUMBER(2) DEFAULT 1 CHECK (aggression_level BETWEEN 1 AND 10),
    diversification     NUMBER(3) DEFAULT 5 CHECK (diversification >= 1),
    max_investment_pct  NUMBER(5,2) DEFAULT 25 CHECK (max_investment_pct BETWEEN 1 AND 100),
    risk_tolerance      NUMBER(2) DEFAULT 3 CHECK (risk_tolerance BETWEEN 1 AND 10),

    CONSTRAINT fk_botconfigs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE orders_active (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id        NUMBER NOT NULL,
    user_id         NUMBER NOT NULL,
    trade_id        NUMBER,
    created_at      DATE DEFAULT SYSDATE,
    order_type      VARCHAR2(10) CHECK (order_type IN ('BUY', 'SELL')),
    price           NUMBER(14,2) CHECK (price >= 0),
    quantity        NUMBER(10) CHECK (quantity > 0),
    is_active       CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('Y', 'N')),

    CONSTRAINT fk_order_stock FOREIGN KEY (stock_id) REFERENCES stocks(id),
    CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_orders_active_user ON orders_active(user_id);
CREATE INDEX idx_orders_active_stock ON orders_active(stock_id);
CREATE INDEX idx_orders_active_type ON orders_active(order_type);
CREATE INDEX idx_orders_active_status ON orders_active(is_active);

CREATE TABLE orders_history (
    id              NUMBER PRIMARY KEY,
    stock_id        NUMBER NOT NULL,
    user_id         NUMBER NOT NULL,
    trade_id        NUMBER,
    created_at      DATE,
    closed_at       DATE DEFAULT SYSDATE,
    order_type      VARCHAR2(10) CHECK (order_type IN ('BUY', 'SELL')),
    price           NUMBER(14,2),
    quantity        NUMBER(10),
    status          VARCHAR2(15) CHECK (status IN ('TRADED','CANCELLED')),

    CONSTRAINT fk_orderhist_stock FOREIGN KEY (stock_id) REFERENCES stocks(id),
    CONSTRAINT fk_orderhist_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_orders_hist_user ON orders_history(user_id);
CREATE INDEX idx_orders_hist_stock ON orders_history(stock_id);
CREATE INDEX idx_orders_hist_status ON orders_history(status);